/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegovida;

import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class Juego_Vida extends javax.swing.JFrame {

    private int numeroCelulas; //Representa el número de celulas en x e y
    private Generacion uno;
    private Generacion dos;
    private int opcion; // indica si la generación se ha creado con los valores del usuario(1) o aleatoriamente(2)
    

    public Juego_Vida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNumCel = new javax.swing.JTextField();
        botonValidar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        siguienteGen = new javax.swing.JButton();
        botonAleatorio = new javax.swing.JButton();
        panelIzquierdo = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        generacionActual = new javax.swing.JLabel();
        generacionAnterior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelSuperior.setBackground(new java.awt.Color(242, 128, 90));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        jLabel1.setText("Introduce el número de células:");

        botonValidar.setBackground(new java.awt.Color(254, 254, 254));
        botonValidar.setForeground(new java.awt.Color(1, 1, 1));
        botonValidar.setText("Validar");
        botonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValidarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Alef", 1, 24)); // NOI18N
        jLabel2.setText("¡Bienvenido al Juego de la vida!");

        siguienteGen.setText("siguiente generación");
        siguienteGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteGenActionPerformed(evt);
            }
        });

        botonAleatorio.setText("Generación aleatoria");
        botonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAleatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(99, 99, 99)
                .addComponent(botonSalir)
                .addContainerGap())
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(siguienteGen, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelNumCel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonValidar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(botonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNumCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteGen)
                    .addComponent(botonAleatorio))
                .addContainerGap())
        );

        panelIzquierdo.setBackground(new java.awt.Color(44, 219, 219));

        javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
        panelIzquierdo.setLayout(panelIzquierdoLayout);
        panelIzquierdoLayout.setHorizontalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        panelIzquierdoLayout.setVerticalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        panelDerecho.setBackground(new java.awt.Color(87, 116, 213));

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        generacionActual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        generacionActual.setText("Generación: ");

        generacionAnterior.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        generacionAnterior.setText("Generación Anterior: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(generacionActual)
                        .addGap(201, 201, 201)
                        .addComponent(generacionAnterior))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(panelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generacionActual)
                    .addComponent(generacionAnterior))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método paara borrar lo que puedan tener los paneles de celulas
    public void resetPaneles() {
        panelDerecho.removeAll();
        panelIzquierdo.removeAll();
        panelDerecho.repaint();
        panelIzquierdo.repaint();
    }


    private void botonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValidarActionPerformed
        opcion=1;
        if (validarNumeroCelulas()) {
            //Borro lo paneles
            this.resetPaneles();

            // Creo la generación
            uno = new Generacion(numeroCelulas);

            //Establezco el layout del panel
            panelIzquierdo.setLayout(new GridLayout(numeroCelulas, numeroCelulas));

            for (int i = 0; i < numeroCelulas; i++) {
                for (int j = 0; j < numeroCelulas; j++) {
                    Celula tmp = new Celula();
                    tmp.setToolTipText(Integer.toString(i) + "," + Integer.toString(j));
                    tmp.addActionListener(e -> click(tmp));

                    uno.ponerCelula(i, j, tmp);
                    panelIzquierdo.add(uno.getCelula(i, j));
                }
            }

            panelIzquierdo.validate();

        } else {
            JOptionPane.showMessageDialog(this, "Número incorrecto o mal formateado");

        }
    }//GEN-LAST:event_botonValidarActionPerformed

    public void click(Celula tmp) {
        if (tmp.isEstado()) {
            tmp.matarCelula();
        } else {
            tmp.resucitarCelula();
        }
    }

    //Miramos si lo que mete en la caja de texto es o no un número
    public boolean esNumero(String aux) {
        try {

            Integer.parseInt(aux);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }

    public boolean validarNumeroCelulas() {
        if (esNumero(labelNumCel.getText())) {
            numeroCelulas = Integer.parseInt(labelNumCel.getText());
            if (numeroCelulas >= 5 && numeroCelulas <= 70) {
                return true;
            }
        }
        return false;
    }

    //Añadimos  un action 
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAleatorioActionPerformed
        opcion=2;
        int numero= Generacion.tamañoAleatorioMatriz();
        if (numero<=70) {
            //Borro lo paneles
            this.resetPaneles();

            // Creo la generación
            uno = new Generacion(numero);

            //Establezco el layout del panel
            panelIzquierdo.setLayout(new GridLayout(numero, numero));

            for (int i = 0; i < numero; i++) {
                for (int j = 0; j < numero; j++) {
                    int estado = Generacion.generarEstado(); //hago una llamda al método generarEstado() para establecer si la celula estará viva o muerta
                    Celula tmp = Celula.generarCelula(estado); 
                    tmp.setToolTipText(Integer.toString(i) + "," + Integer.toString(j));
                    tmp.addActionListener(e -> click(tmp));

                    uno.ponerCelula(i, j, tmp);
                    panelIzquierdo.add(uno.getCelula(i, j));
                    
                }
            }

            panelIzquierdo.validate();


        }



    }//GEN-LAST:event_botonAleatorioActionPerformed

    private void siguienteGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteGenActionPerformed
        System.out.println("Generación ");
        
        if (opcion==1) {
            JOptionPane.showMessageDialog(null, "Generación por valores");
            
            
        }else if (opcion==2){
           JOptionPane.showMessageDialog(null, "Generación Aleatoria");
        }
        
        
    }//GEN-LAST:event_siguienteGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego_Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego_Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego_Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego_Vida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego_Vida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAleatorio;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonValidar;
    private javax.swing.JLabel generacionActual;
    private javax.swing.JLabel generacionAnterior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField labelNumCel;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JButton siguienteGen;
    // End of variables declaration//GEN-END:variables
}
